/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;

import com.sun.jdi.connect.spi.Connection;
import java.sql.DriverManager;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class barrowBook extends javax.swing.JFrame {

    /**
     * Creates new form barrowBook
     */
    public barrowBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("EMPOYEE ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 308, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("BOOK ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 265, 95, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("EXPECTED RETURN DAY -");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 388, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 237, 225));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 262, 71, -1));

        jTextField2.setBackground(new java.awt.Color(255, 237, 225));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 305, 71, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 388, 175, 16));

        jButton1.setBackground(new java.awt.Color(252, 188, 157));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("BARROW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jButton2.setBackground(new java.awt.Color(252, 188, 157));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        jButton3.setBackground(new java.awt.Color(252, 188, 157));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("BORROW BOOK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI\\OneDrive\\Pictures\\Video Projects\\Hand_giving_book__Exchange_books-removebg-preview.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String url = "jdbc:mysql://localhost:3306/Library_management";
String user = "root";
String password = "1234";

try {
    // Establish a database connection
    java.sql.Connection conn = DriverManager.getConnection(url, user, password);

    // SQL to create the table if it does not exist
    String createTableSQL = "CREATE TABLE IF NOT EXISTS barroBook ("
                          + "book_id VARCHAR(50), "
                          + "employee_id VARCHAR(50), "
                          + "date DATE)";
    
    java.sql.Statement stmt = conn.createStatement();
    stmt.executeUpdate(createTableSQL); // Execute the create table command
    
    // Data to insert (replace these with your actual data or text fields' input)
    String bookId = jTextField1.getText(); // Book ID input
    String employeeId = jTextField2.getText(); // Employee ID input

    // Check if book_id exists in books table
    String checkBookSQL = "SELECT COUNT(*) FROM books WHERE ID = ?";
    java.sql.PreparedStatement checkBookStmt = conn.prepareStatement(checkBookSQL);
    checkBookStmt.setString(1, bookId);
    java.sql.ResultSet bookResult = checkBookStmt.executeQuery();
    bookResult.next();
    boolean bookExists = bookResult.getInt(1) > 0;
    bookResult.close();
    checkBookStmt.close();

    // Check if employee_id exists in employee table
    String checkEmployeeSQL = "SELECT COUNT(*) FROM employee WHERE id = ?";
    java.sql.PreparedStatement checkEmployeeStmt = conn.prepareStatement(checkEmployeeSQL);
    checkEmployeeStmt.setString(1, employeeId);
    java.sql.ResultSet employeeResult = checkEmployeeStmt.executeQuery();
    employeeResult.next();
    boolean employeeExists = employeeResult.getInt(1) > 0;
    employeeResult.close();
    checkEmployeeStmt.close();

    // Check if both IDs exist and show a single message if either does not
    if (!bookExists && !employeeExists) {
        JOptionPane.showMessageDialog(null, "Both Book ID and Employee ID do not exist.", "Error", JOptionPane.ERROR_MESSAGE);
    } else if (!bookExists) {
        JOptionPane.showMessageDialog(null, "Book ID does not exist.", "Error", JOptionPane.ERROR_MESSAGE);
    } else if (!employeeExists) {
        JOptionPane.showMessageDialog(null, "Employee ID does not exist.", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        // Get the current date
        LocalDate currentDate = LocalDate.now();

        // Prepare SQL statement for inserting data with current date
        String insertSQL = "INSERT INTO barroBook (book_id, employee_id, date) VALUES (?, ?, ?)";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(insertSQL);

        // Set parameters for book and employee IDs and date
        pstmt.setString(1, bookId);
        pstmt.setString(2, employeeId);
        pstmt.setDate(3, java.sql.Date.valueOf(currentDate));

        // Execute the insert statement
        int rowsInserted = pstmt.executeUpdate();

        if (rowsInserted > 0) {
            // Show a success message
            JOptionPane.showMessageDialog(null, "Successfully borrowed the book!");

            // Calculate the return date (14 days from now)
            LocalDate futureDate = currentDate.plusDays(14);

            // Format and display the return date in jLabel4
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String formattedDate = futureDate.format(formatter);
            jLabel4.setText("Return by: " + formattedDate);

            // Update the copies count in the books table
            String updateCopiesSQL = "UPDATE books SET copies = copies - 1 WHERE ID = ? AND copies > 0";
            java.sql.PreparedStatement updateCopiesStmt = conn.prepareStatement(updateCopiesSQL);
            updateCopiesStmt.setString(1, bookId);
            int rowsUpdated = updateCopiesStmt.executeUpdate();

            if (rowsUpdated == 0) {
                JOptionPane.showMessageDialog(null, "No available copies to borrow.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            
            updateCopiesStmt.close();
        } else {
            JOptionPane.showMessageDialog(null, "Borrowing failed.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Close resources
        pstmt.close();
    }

    stmt.close();
    conn.close();
} catch (Exception e) {
    e.printStackTrace();
}




    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Dashboard dash = new Dashboard();
         dash.setVisible(true);

        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         jTextField1.setText(""); // Clears text in jTextField1
    jTextField2.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barrowBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
